name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  node-ci:
    uses: ./.github/workflows/node-ci-reusable.yml
    with:
      node-version: '20'
      working-directory: '.'
      run-lint: true
      run-test: true
      run-build: true
